options:
  plumgrid-virtual-ip:
    default: 192.168.100.250
    type: string
    description: IP address of the Director's Management interface. Same IP can be used to access PG Console.
  plumgrid-username:
    default: plumgrid
    type: string
    description: Username to access PLUMgrid Director
  plumgrid-password:
    default: plumgrid
    type: string
    description: Password to access PLUMgrid Director
  lcm-ssh-key:
    default: 'null'
    type: string
    description: Public SSH key of PLUMgrid LCM which is running PG-Tools.
  mgmt-interface:
    type: string
    description: The interface connected to PLUMgrid Managment network.
  fabric-interfaces:
    default: 'MANAGEMENT'
    type: string
    description: |
       Interfaces that will provide fabric connectivity on the director nodes.
       Provided in form of json in a string. Default value is MANAGEMENT which
       will configure the management interface as the fabric interface on each
       director.
  network-device-mtu:
    type: string
    default: '1580'
    description: The MTU size for interfaces managed by director.
  install_sources:
    default: 'ppa:plumgrid-team/stable'
    type: string
    description: Provide the install source from where to install the PLUMgrid debs.
  install_keys:
    default: null
    type: string
    description: Provide the respective keys of the install sources.
  plumgrid-build:
    default: 'latest'
    type: string
    description: |
       Provide the build version of PLUMgrid packages that needs to be installed
  iovisor-build:
    default: 'latest'
    type: string
    description: |
       Provide the build version of iovisor package that needs to be installed
  plumgrid-license-key:
    default: null
    type: string
    description: Provide the PLUMgrid ONS License key.
  opsvm-ip:
    default: 127.0.0.1
    type: string
    description: IP address of the PLUMgrid Operations VM Management interface.
  lcm-ip:
    type: string
    description: IP used by Solutions API to get/post cloud information.
  sapi-port:
    default: 8099
    type: int
    description: Port used by Solutions API to get/post cloud information.
  sapi-zone:
    default: pgzone
    type: string
    description: Zone name used by Solutions API to get/post cloud information.
